development:
  adapter: sqlite3
  database: db/development.sqlite3

uat:
  adapter: sqlite3
  database: db/uat.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
